version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run: java --version
      - store_artifacts:
          path: my-app.jar
          destination: my-app-${CIRCLE_BUILD_NUM}.jar

  test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
          prefix: test-results/
          persist_to_workspace:
            root: ~/circleci-showcase
            paths:
              - target/surefire-reports
          when: always
          artifacts:
            paths:
              - target/surefire-reports

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build