version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run: java --version

  test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test
          working_directory: ~/repo
      - store_test_results:
          path: target/surefire-reports
          prefix: test-results/
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target/surefire-reports
      - when: always
        artifacts:
          paths:
            - target/surefire-reports
