version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run: java --version

  test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run: mvn test
