version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run: java --version

  test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test
      - store_test_results:
          path: test-results

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build